### ISSUE TITLE
Сделать анимацию переключения кнопок play/pause

### ISSUE THREAD

**Issue by web-crab** [YourFavoriteMusicDealer/web#21]
Анимация кнопок:
https://cloud.mail.ru/public/8Z36/XkFMUJCcx

Читать [тут](https://ru.vuejs.org/v2/guide/transitions.html)

**Comment by jonkofee** [comment]
![kapture 2018-05-18 at 15 44 36](https://user-images.githubusercontent.com/9060043/40235370-bc142306-5ab2-11e8-80eb-787dac34c707.gif)

Не знаю как в других браузерах, но в Safari так

**Comment by jonkofee** [comment]
Вот так должна работать анимация
![kapture 2018-05-19 at 18 13 53](https://user-images.githubusercontent.com/9060043/40270123-6fa4f336-5b90-11e8-9de7-c76fef9fdd86.gif)

**Comment by cherja** [comment]
# У меня снова телеграмм откл(((
[https://jsfiddle.net/0jnhhv4m/](url)
Как на счет такой задумки?

**Comment by cherja** [comment]
Вот так при нажатии будет пауза у анимации.
[https://jsfiddle.net/0mLzwwus/](url)

**Comment by cherja** [comment]
https://jsfiddle.net/983ac9hv/1/

**Comment by cherja** [comment]
Вот так при зажатии бут анимация на паузе)

[https://jsfiddle.net/983ac9hv/1/](url)

**Comment by cherja** [comment]
Как на счёт такого?У меня телега не работает...
[https://jsfiddle.net/983ac9hv/1/](url)

**Comment by cherja** [comment]
[https://jsfiddle.net/983ac9hv/2/](url)

**Comment by cherja** [comment]
https://jsfiddle.net/fojv8m31/1/
